//TODO ACTIONS
const ADD_TODO = "todos/ADD_TODO";
const DELETE_TODO = "todos/DELETE_TODO";
const EDIT_TODO = "todos/EDIT_TODO";
const TOGGLE_TODO_STATUS = "todos/TOGGLE_TODO_STATUS";

//FILTER ACTIONS
const SEARCH_FILTER_CHANGED = "todos/SEARCH_FILTER_CHANGED";
const STATUS_FILTER_CHANGED = "todos/STATUS_FILTER_CHANGED";
const PRIORITIY_FILTER_CHANGED = "todos/PRIORITY_FILTER_CHANGED";
