//TODO ACTIONS
export const ADD_TODO = "todos/ADD_TODO";
export const DELETE_TODO = "todos/DELETE_TODO";
export const EDIT_TODO = "todos/EDIT_TODO";
export const TOGGLE_TODO_STATUS = "todos/TOGGLE_TODO_STATUS";

//FILTER ACTIONS
export const SEARCH_FILTER_CHANGED = "todos/SEARCH_FILTER_CHANGED";
export const STATUS_FILTER_CHANGED = "todos/STATUS_FILTER_CHANGED";
export const PRIORITIES_FILTER_CHANGED = "todos/PRIORITY_FILTER_CHANGED";
